language: c
compiler: clang
env: CONFIG=release OS=linux ARCH=32
before_install: sudo apt-get install g++-multilib valgrind
script: >
        make print all &&
        make --keep-going print-tests tests-all
